/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CafeInfo = IDL.Record({
  'contact' : IDL.Text,
  'hours' : IDL.Text,
  'address' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPopular' : IDL.Bool,
  'category' : IDL.Text,
  'priceCents' : IDL.Nat,
});
export const Photo = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'category' : IDL.Text,
});
export const Review = IDL.Record({
  'content' : IDL.Text,
  'date' : Time,
  'reviewerName' : IDL.Text,
  'rating' : IDL.Nat8,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Text, IDL.Nat8, IDL.Text], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([Time], [], []),
  'getCafeInfo' : IDL.Func([], [CafeInfo], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'initializeAdmin' : IDL.Func([], [], []),
  'updateCafeInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CafeInfo = IDL.Record({
    'contact' : IDL.Text,
    'hours' : IDL.Text,
    'address' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPopular' : IDL.Bool,
    'category' : IDL.Text,
    'priceCents' : IDL.Nat,
  });
  const Photo = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'category' : IDL.Text,
  });
  const Review = IDL.Record({
    'content' : IDL.Text,
    'date' : Time,
    'reviewerName' : IDL.Text,
    'rating' : IDL.Nat8,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Text, IDL.Nat8, IDL.Text], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([Time], [], []),
    'getCafeInfo' : IDL.Func([], [CafeInfo], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'initializeAdmin' : IDL.Func([], [], []),
    'updateCafeInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };