/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CafeInfo {
  'contact' : string,
  'hours' : string,
  'address' : string,
}
export interface MenuItem {
  'name' : string,
  'description' : string,
  'isPopular' : boolean,
  'category' : string,
  'priceCents' : bigint,
}
export interface Photo { 'url' : string, 'title' : string, 'category' : string }
export interface Review {
  'content' : string,
  'date' : Time,
  'reviewerName' : string,
  'rating' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addMenuItem' : ActorMethod<
    [string, string, string, bigint, boolean],
    undefined
  >,
  'addPhoto' : ActorMethod<[string, string, string], undefined>,
  'addReview' : ActorMethod<[string, number, string], undefined>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[Time], undefined>,
  'getCafeInfo' : ActorMethod<[], CafeInfo>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getPhotos' : ActorMethod<[], Array<Photo>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'initializeAdmin' : ActorMethod<[], undefined>,
  'updateCafeInfo' : ActorMethod<[string, string, string], undefined>,
  'updateMenuItem' : ActorMethod<
    [string, string, string, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];